import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProductContextProvider from "./context/productContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product Context",
  description: "Generated by Muhammad Usman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProductContextProvider>
          {children}
        </ProductContextProvider>
      </body>
    </html>
  );
}
